server:
  port: 8080

spring:
  datasource:
    url: jdbc:dm://${DB_HOST:localhost}:${DB_PORT:5236}/${DB_NAME:DAMENG}
    username: ${DB_USER:SYSDBA}
    password: ${DB_PASSWORD:SYSDBA001}
    driver-class-name: dm.jdbc.driver.DmDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DmDialect

blade:
  name: hub-backend
  env: dev
  is-dev: true
  service:
    name: ${spring.application.name}
